### ISSUE TITLE
Invalid alias in ArcGIS Python Toolbox

### ISSUE THREAD

**Issue by lpinner** [fiftysevendegreesofrad/sdna_plus#95]
The sDNA ArcGIS python [toolbox alias](https://github.com/fiftysevendegreesofrad/sdna_plus/blob/729bd9824a7463fb2089fef3154bf6f6447a6e0a/arcscripts/sDNA.pyt#L146) is invalid:

`self.alias = "Spatial Design Network Analysis"`

From the [ArcGIS documentation](https://pro.arcgis.com/en/pro-app/latest/arcpy/geoprocessing_and_python/a-template-for-python-toolboxes.htm): 

> toolbox alias must begin with a letter (a-z, A-Z) and can only consist of letters and numbers (0-9). Spaces and special characters are not allowed (for example, _, !, @, #, $, %, -).

So when users try to use the toolbox from within a script with [`arcpy.ImportToolbox`](https://pro.arcgis.com/en/pro-app/latest/arcpy/functions/importtoolbox.htm), python will raise a SyntaxError [if they try to use the invalid alias](https://gis.stackexchange.com/questions/457693/performing-analysis-with-sdna-toolbox-using-arcgis-notebook)). 

Suggest you change the alias to:

`self.alias = "sDNA"`

For users coming across this issue, a workaround is to use the `module_name` parameter to set a valid temporary alias when calling `arcpy.ImportToolbox`.

**Comment by JamesParrott** [comment]
@lpinner Thanks Luke.  We'll discuss this at the next opportunity.  Are you happy to use the work around for the time being?

**Comment by JamesParrott** [comment]
Completed by faabe8a.

Feel free to re-open this if the changes didn't do the trick.
